# Gunicorn production config — generated by install-full-saas.sh
# workers MUST remain 1: SessionManager is an in-memory singleton.
# Multiple workers would create separate SessionManager instances,
# breaking session routing and causing data loss.
workers = 1
worker_class = "gthread"
threads = 32
timeout = 120
keepalive = 5
graceful_timeout = 30

bind = "127.0.0.1:5001"

worker_tmp_dir = "/tmp/gunicorn"

accesslog = "/var/log/tiktok-quiz-saas/saas-access.log"
errorlog  = "/var/log/tiktok-quiz-saas/saas-error.log"
loglevel  = "info"
